version: "3"

services:
  postgres:
    image: postgres:11.6-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sample
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data"

volumes:
  db_data:
